---
- name: Add jessie backports
  apt_repository:
    repo: deb http://ftp.debian.org/debian jessie-backports main contrib non-free
    state: present
    filename: 'backports'
  register: jbp_added
  become: yes

- name: update the apt cache
  apt: update_cache=yes cache_valid_time=7200
  become: yes

# if jessie-backports has been added we should update the cache
- name: force update the apt cache
  apt: update_cache=yes
  when: jbp_added.changed
  become: yes

- name: install certbot from backports
  become: yes # needed to install apt packages
  apt:
    allow_unauthenticated: no
    autoclean: yes
    autoremove: yes
    cache_valid_time: 7200
    default_release: jessie-backports
    force: no
    force_apt_get: no
    install_recommends: yes
    name: ["certbot"]
    only_upgrade: no
    purge: no
    state: present
    update_cache: yes
  tags: apt

- name: change the path to letsencrypt
  set_fact:
    letsencrypt_path: "/usr/bin/letsencrypt"
