---
- name: update the apt cache
  apt: update_cache=yes cache_valid_time=7200
  become: yes

- name: install certbot
  become: yes # needed to install apt packages
  apt:
    allow_unauthenticated: no
    autoclean: yes
    autoremove: yes
    cache_valid_time: 7200
    force: no
    force_apt_get: no
    install_recommends: yes
    name: ["certbot"]
    only_upgrade: no
    purge: no
    state: present
    update_cache: yes
  tags: apt

- name: change the path to letsencrypt
  set_fact:
    letsencrypt_path: "/usr/bin/letsencrypt"
